ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Product:index }
ecommerce_product_view:
    path:     /product
    defaults: { _controller: EcommerceBundle:Product:view }